name: Desplegar en Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache de capas Docker
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Iniciar sesión en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA .

      - name: Subir imagen Docker a ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA

      - name: Desplegar en ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          image: ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA
          region: ${{ secrets.AWS_REGION }}